"""making new tables

Revision ID: 14b20921ba5d
Revises: c6a752b566e0
Create Date: 2024-05-09 08:59:07.378484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b20921ba5d'
down_revision = 'c6a752b566e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('user_password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('image',
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('image_catagroy', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('user')
    # ### end Alembic commands ###
