"""Initial migration.

Revision ID: 2ecfd8dc852f
Revises: 93574fcb9cec
Create Date: 2024-05-12 14:49:05.178906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecfd8dc852f'
down_revision = '93574fcb9cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('user_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_password', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
