"""empty message

Revision ID: 3961d32dc7d7
Revises: 
Create Date: 2024-04-30 21:12:59.198975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3961d32dc7d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('user_password', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('image',
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('image_catagroy', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('user')
    # ### end Alembic commands ###
