"""changing username to id

Revision ID: 557f48ad017d
Revises: 14b20921ba5d
Create Date: 2024-05-10 13:53:58.042704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557f48ad017d'
down_revision = '14b20921ba5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('user_password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('image',
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('image_catagroy', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('user')
    # ### end Alembic commands ###
