"""Initial migration.

Revision ID: 93574fcb9cec
Revises: dfb6cf570fa5
Create Date: 2024-05-12 09:20:20.086192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93574fcb9cec'
down_revision = 'dfb6cf570fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_user',
    sa.Column('user_password', sa.VARCHAR(length=10), nullable=False),
    sa.Column('id', sa.VARCHAR(length=10), nullable=False)
    )
    # ### end Alembic commands ###
