"""user table added

Revision ID: c6a752b566e0
Revises: 3961d32dc7d7
Create Date: 2024-05-07 15:43:48.278763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a752b566e0'
down_revision = '3961d32dc7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.alter_column('user_password',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_unique_constraint("user_info", ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_password',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('username')

    op.create_table('_alembic_tmp_user',
    sa.Column('user_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('user_password', sa.VARCHAR(length=80), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username', name='unique_name')
    )
    # ### end Alembic commands ###
