"""Initial migration.

Revision ID: dfb6cf570fa5
Revises: 3792bfbc6e27
Create Date: 2024-05-11 20:14:53.710664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb6cf570fa5'
down_revision = '3792bfbc6e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', column_name ='user_id', new_column_name='id')
       

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
