"""initial migration

Revision ID: f69bec61f14a
Revises: f21f1eef6320
Create Date: 2024-05-08 19:08:57.906287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69bec61f14a'
down_revision = 'f21f1eef6320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
